name = "flappypi-auth"
main = "worker-fast-entry.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "flappypi"
database_id = "6bcb42bd-529f-4af5-bd4d-882c4e91790b"

[[queues.producers]]
binding = "GAME_POINTS_QUEUE"
queue = "flappypi-game-points"

[[queues.consumers]]
queue = "flappypi-game-points"
max_batch_size = 100
max_batch_timeout = 20
max_retries = 10
max_concurrency = 1
dead_letter_queue = "flappypi-game-points-dlq"

[[r2_buckets]]
binding = "GAME_PHOTOS"
bucket_name = "flappypi-game-photos"

[vars]
ENV = "dev"

# ================================
# ENVIRONMENT: QA
# ================================
[env.qa]
name = "flappypi-auth-qa"
routes = [
  { pattern = "qa.auth.flappypi.com/*", zone_name = "flappypi.com" }
]

[env.qa.vars]
ENV = "qa"

[[env.qa.d1_databases]]
binding = "DB"
database_name = "flappypi_qa"
database_id = "efcadca4-7074-42ae-b1e2-8595073e5d55"

[[env.qa.queues.producers]]
binding = "GAME_POINTS_QUEUE"
queue = "flappypi-game-points-qa"

[[env.qa.queues.consumers]]
queue = "flappypi-game-points-qa"
max_batch_size = 100
max_batch_timeout = 20
max_retries = 10
max_concurrency = 1
dead_letter_queue = "flappypi-game-points-qa-dlq"

[[env.qa.r2_buckets]]
binding = "GAME_PHOTOS"
bucket_name = "flappypi-game-photos-qa"
